name: CD Pipeline

on:
    push:
        branches:
            main

jobs:
    deploy:
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Set up Node js
              uses: actions/setup-node@v3
              with:
                node-verison: 23

            - name: Install Vercel CLI
              run: npm install -g vercel

            - name: Install Dependencies
              run: npm install

            - name: Adding Secret Keys
              run: node ./config.js 
              env:
                ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
                SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}


            - name: Deploy on Vercel
              run: vercel --prod
              env: 
                VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}